"""
Django settings for factory project.

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load backend/factory/.env for local DB credentials (hosting uses injected env vars).
try:
    from dotenv import load_dotenv
    load_dotenv(BASE_DIR / '.env', override=True)
except ImportError:
    pass


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-fallback-for-local')

# Hosting: leave unset or DEBUG=False. Local: set DEBUG=True if you want detailed errors.
DEBUG = os.environ.get('DEBUG', 'False').lower() in ('1', 'true', 'yes')

ALLOWED_HOSTS = ['*',]


# Application definition

INSTALLED_APPS = [
    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt',
    'fact_app',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

# Custom User Model
AUTH_USER_MODEL = 'fact_app.Employee'

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', 
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
# CORS Configuration - Allow local development and production
import os

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "https://factory-project-production.up.railway.app",
    "https://friendly-purpose-production-9a5b.up.railway.app",  
]
CSRF_TRUSTED_ORIGINS = [
    'https://factory-project-production.up.railway.app',
    'http://localhost:5173',
    'http://127.0.0.1:5173',
]

# Allow additional origins from environment variable (for production)
# Set CORS_EXTRA_ORIGINS in your PythonAnywhere environment
# Example: CORS_EXTRA_ORIGINS=https://your-app.vercel.app,https://www.yourdomain.com
CORS_EXTRA_ORIGINS = os.environ.get('CORS_EXTRA_ORIGINS', '').split(',')
CORS_ALLOWED_ORIGINS.extend([origin.strip() for origin in CORS_EXTRA_ORIGINS if origin.strip()])

# Allow Vercel preview / deployment domains (e.g. https://my-app-abc123.vercel.app)
# If you have a custom domain, prefer adding it explicitly via CORS_EXTRA_ORIGINS.
CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^https://.*\.vercel\.app$",
]

# For development, you can also use this (NOT recommended for production):
# CORS_ALLOW_ALL_ORIGINS = True  # Only use this in development!

ROOT_URLCONF = 'factory.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'factory.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
#
# Local (default): PostgreSQL `factory` on localhost:5432
# Production/Aiven: set DJANGO_ENV=production (and DATABASE_URL or DB_* vars)
# Backward compatible: if DJANGO_ENV is unset and DATABASE_URL is set, use remote DB

DJANGO_ENV = os.environ.get("DJANGO_ENV", "").strip().lower()
DATABASE_URL = os.environ.get("DATABASE_URL", "").strip()

if DJANGO_ENV in ("production", "prod"):
    _use_remote_db = True
elif DJANGO_ENV in ("local", "development", "dev"):
    _use_remote_db = False
else:
    # Unset DJANGO_ENV → previous behavior (DATABASE_URL means hosted DB)
    _use_remote_db = bool(DATABASE_URL)

if _use_remote_db:
    if DATABASE_URL:
        db_config = dj_database_url.config(
            default=DATABASE_URL,
            conn_max_age=600,
            ssl_require=True,
        )
    else:
        db_config = {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.environ.get("DB_NAME", ""),
            "USER": os.environ.get("DB_USER", ""),
            "PASSWORD": (
                os.environ.get("DB_PASSWORD")
                or os.environ.get("POSTGRES_PASSWORD")
                or ""
            ).strip(),
            "HOST": os.environ.get("DB_HOST", ""),
            "PORT": os.environ.get("DB_PORT", "5432"),
            "CONN_MAX_AGE": 600,
        }
    # Aiven / hosted PostgreSQL requires SSL
    db_config.setdefault("OPTIONS", {})
    db_config["OPTIONS"]["sslmode"] = "require"
    DATABASES = {"default": db_config}
else:
    # Local development PostgreSQL (no SSL)
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.environ.get("DB_NAME", "factory"),
            "USER": os.environ.get("DB_USER", "postgres"),
            "PASSWORD": (
                os.environ.get("DB_PASSWORD")
                or os.environ.get("POSTGRES_PASSWORD")
                or ""
            ).strip(),
            "HOST": os.environ.get("DB_HOST", "localhost"),
            "PORT": os.environ.get("DB_PORT", "5432"),
        }
    }




# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'whitenoise.storage.StaticFilesStorage'
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

# JWT Settings
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'employee_id',
    'USER_ID_CLAIM': 'user_id',
}
