# Generated by Django 3.2.25 on 2025-12-18 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fact_app', '0000_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('vendor_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('material_id', models.AutoField(primary_key=True, serialize=False)),
                ('material', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('measuring_unit', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_materials', to='fact_app.vendor')),
            ],
        ),
    ]
